name: Test and Build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    
    - name: Cache Yarn modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-   
 
    - name: Install dependencies
      run: yarn install
    
    - name: Run tests
      run: yarn test:ci

    - name: Build
      run: NODE_OPTIONS=--openssl-legacy-provider yarn build
